server:
  port: 8080
  servlet:
      context-path: /devoox
      jsp:
        registered: false
  error:
    whitelabel: 
      enabled: false
    
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/devoox?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=CET
    username: root
    password: root
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
       ddl-auto: none
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
